global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "diet-assistant-prod"
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ["diet-assistant.onrender.com"]

remote_write:
  - url: ${GRAFANA_REMOTE_WRITE_URL}
    basic_auth:
      username: ${GRAFANA_REMOTE_WRITE_USERNAME}
      password: ${GRAFANA_REMOTE_WRITE_PASSWORD}
